//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static System.Drawing.Bitmap Back {
            get {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Hearts10 {
            get {
                object obj = ResourceManager.GetObject("Hearts10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Hearts2 {
            get {
                object obj = ResourceManager.GetObject("Hearts2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Hearts3 {
            get {
                object obj = ResourceManager.GetObject("Hearts3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Hearts4 {
            get {
                object obj = ResourceManager.GetObject("Hearts4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Hearts5 {
            get {
                object obj = ResourceManager.GetObject("Hearts5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Hearts6 {
            get {
                object obj = ResourceManager.GetObject("Hearts6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Hearts7 {
            get {
                object obj = ResourceManager.GetObject("Hearts7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Hearts8 {
            get {
                object obj = ResourceManager.GetObject("Hearts8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Hearts9 {
            get {
                object obj = ResourceManager.GetObject("Hearts9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap HeartsAce {
            get {
                object obj = ResourceManager.GetObject("HeartsAce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap HeartsQueen {
            get {
                object obj = ResourceManager.GetObject("HeartsQueen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap HeartsKing {
            get {
                object obj = ResourceManager.GetObject("HeartsKing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap HeartsJack {
            get {
                object obj = ResourceManager.GetObject("HeartsJack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Diamonds10 {
            get {
                object obj = ResourceManager.GetObject("Diamonds10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Diamonds2 {
            get {
                object obj = ResourceManager.GetObject("Diamonds2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Diamonds3 {
            get {
                object obj = ResourceManager.GetObject("Diamonds3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Diamonds4 {
            get {
                object obj = ResourceManager.GetObject("Diamonds4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Diamonds5 {
            get {
                object obj = ResourceManager.GetObject("Diamonds5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Diamonds6 {
            get {
                object obj = ResourceManager.GetObject("Diamonds6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Diamonds7 {
            get {
                object obj = ResourceManager.GetObject("Diamonds7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Diamonds8 {
            get {
                object obj = ResourceManager.GetObject("Diamonds8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Diamonds9 {
            get {
                object obj = ResourceManager.GetObject("Diamonds9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap DiamondsAce {
            get {
                object obj = ResourceManager.GetObject("DiamondsAce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap DiamondsQueen {
            get {
                object obj = ResourceManager.GetObject("DiamondsQueen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap DiamondsKing {
            get {
                object obj = ResourceManager.GetObject("DiamondsKing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap DiamondsJack {
            get {
                object obj = ResourceManager.GetObject("DiamondsJack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Spades10 {
            get {
                object obj = ResourceManager.GetObject("Spades10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Spades2 {
            get {
                object obj = ResourceManager.GetObject("Spades2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Spades3 {
            get {
                object obj = ResourceManager.GetObject("Spades3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Spades4 {
            get {
                object obj = ResourceManager.GetObject("Spades4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Spades5 {
            get {
                object obj = ResourceManager.GetObject("Spades5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Spades6 {
            get {
                object obj = ResourceManager.GetObject("Spades6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Spades7 {
            get {
                object obj = ResourceManager.GetObject("Spades7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Spades8 {
            get {
                object obj = ResourceManager.GetObject("Spades8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Spades9 {
            get {
                object obj = ResourceManager.GetObject("Spades9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SpadesAce {
            get {
                object obj = ResourceManager.GetObject("SpadesAce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SpadesQueen {
            get {
                object obj = ResourceManager.GetObject("SpadesQueen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SpadesKing {
            get {
                object obj = ResourceManager.GetObject("SpadesKing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SpadesJack {
            get {
                object obj = ResourceManager.GetObject("SpadesJack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Clubs10 {
            get {
                object obj = ResourceManager.GetObject("Clubs10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Clubs2 {
            get {
                object obj = ResourceManager.GetObject("Clubs2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Clubs3 {
            get {
                object obj = ResourceManager.GetObject("Clubs3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Clubs4 {
            get {
                object obj = ResourceManager.GetObject("Clubs4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Clubs5 {
            get {
                object obj = ResourceManager.GetObject("Clubs5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Clubs6 {
            get {
                object obj = ResourceManager.GetObject("Clubs6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Clubs7 {
            get {
                object obj = ResourceManager.GetObject("Clubs7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Clubs8 {
            get {
                object obj = ResourceManager.GetObject("Clubs8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Clubs9 {
            get {
                object obj = ResourceManager.GetObject("Clubs9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ClubsAce {
            get {
                object obj = ResourceManager.GetObject("ClubsAce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ClubsQueen {
            get {
                object obj = ResourceManager.GetObject("ClubsQueen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ClubsKing {
            get {
                object obj = ResourceManager.GetObject("ClubsKing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ClubsJack {
            get {
                object obj = ResourceManager.GetObject("ClubsJack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
